name: Otonom Fiyat Guncelleme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle # KRİTİK ADIM
        run: |
          pip install requests beautifulsoup4

      - name: Scraper'ı Calistir
        run: python scraper.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name 'Monease Bot'
          git config --global user.email 'bot@monease.com'
          git add prices.json
          git commit -m "Otonom canli guncelleme: $(date)" || exit 0
          git push
